# Generated by Django 3.0.5 on 2020-05-04 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200504_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='order_id',
            new_name='orderId',
        ),
    ]
