# Generated by Django 3.0.5 on 2020-05-04 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200505_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='order_id',
            new_name='orderId',
        ),
    ]
